In [4]:
import numpy as np

In [7]:
#28
# Extraiga la parte entera de un arreglo aleatorio utilizando 5 métodos diferentes
dimension=int(input("Ingrese la dimesion del arreglo: "))
#Diseño de la matriz con la dimension dada al inicio
matriz=np.random.uniform(0,10,dimension)
#Se resta los elementos de la matriz con el resto del la division del matriz con 1
metodo1=matriz - matriz%1
#Se aplica la funcion floor la cual nos devuelve el entero mas cercano por abajode la matriz
metodo2=np.floor(matriz)
#Se aplica la funcion floor la cual nos devuelve el entero mas cercano por arriba de la matriz, por lo que se resta -1 
metodo3=np.ceil(matriz)-1
#Se aplica la funcion astype que cambia el tipo de dato
metodo4=matriz.astype(int)
#Se aplica la funcion trunc la cual nos permite redondear un numero
metodo5 = np.trunc(matriz)
#Impresion de los resultados de los diferentes métodos
print("Resultado funcion 1: ", metodo1)
print("Resultado funcion 2: ", metodo2)
print("Resultado funcion 3: ", metodo3)
print("Resultado funcion 4: ", metodo4)
print("Resultado funcion 5: ", metodo5)

Resultado funcion 1:  [5. 3.]
Resultado funcion 2:  [5. 3.]
Resultado funcion 3:  [5. 3.]
Resultado funcion 4:  [5 3]
Resultado funcion 5:  [5. 3.]


In [10]:
#29
#Crear una matriz 5x5 con valores de fila que van de 0 a 4
matriz = np.zeros((5,5))
#Primero creamos la matriz de 5x5 y con la funcion zeros toda la matriz se la llena con 0
matriz +=np.arange(5)
#Con la funcion arange vamos intercambiando los valores iniciales con numeros que van en un rango de 0 a 4
print(matriz)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [13]:
#31
#Crear un vector de 10 con valores en un rango de 0 a 1, pero excluido el 0 y el 1
matriz=np.linspace(0,1,12,endpoint=True)[1:-1]
#Se utiliza la función linspace genera un array de n elementos, el valor inicial y el final 
print(matriz)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [16]:
#34
#Considere dos matrices aleatorias A y B, verifique si son iguales
dimension = int(input("Ingrese las dimencion que corresponde a las dos matrices: "))
rango = int(input("Ingrese hasta que numero se almacenara en las matrices: "))
matriz1 = np.random.randint(0,rango,dimension)
matriz2 = np.random.randint(0,rango,dimension)
#Se procede a crear las matrices con numero randomicos dentro del rango que se ingrese y con la dimension que se elija 
equal = np.allclose(matriz1 ,matriz2)
#Se utiliza la función allclose la cual compara cada uno de los elementos de los vectores y nos da como resultado un valor booleano el cual true indica que los arreglos son iguales y false que los arreglos no son iguales
print(equal)

False


In [19]:
#41
#¿Como se puede imprimir todos los valores de un arreglo
dimensionx = int(input("Ingrese el numero de filas de la matriz: "))
dimensiony= int(input("Ingrese el numero de columnas de la matriz: "))
np.set_printoptions(threshold=dimensiony)
#Se utiliza la funcion set_printoptions que 
#Se utliza la funcion treshold que 
matriz = np.zeros((dimensionx, dimensiony))
print(matriz)

ValueError: invalid literal for int() with base 10: ''

In [17]:
#55 
#Se crea un arreglo de 10 elementos donde todos son 1
A = np.ones(10, dtype=int) 
#Se crea un arreglo con 10 elementos aleatorios desde 1 hasta 10 (representado por la longitud de A)
B = np.random.randint(1, len(A), 10) 
#Se indexa cada elemento de B contando sus ocurrencias y a estos indices se les suma 1
A += np.bincount(B, minlength=len(A))
print("Vector dado: ")
print(B)
print("Numero de elementos indexados del vector dado sumados 1: ")
print(A) 

Vector dado: 
[1 5 4 ... 1 7 7]
Numero de elementos indexados del vector dado sumados 1: 
[1 3 1 ... 3 1 3]


In [ ]:
#80
#Se crea un arreglo aleatorio de las dimensiones deseadas
A = np.random.randint(1, 100, 20)
#Se selecciona el numero de valores a mostrar
n = 3
#Se imprime el arreglo
print(A)
#Se imprime los n mayores valores del arreglo
#Se uso argsort para ordenar de menor a mayor el arreglo
#De este arreglo ordenado se eligio mostrar los n ultimos elementos
print(A[np.argsort(A)[-n:]])

In [ ]:
#82
#Se crea un arreglo estructurado
A = np.array([("Python", 2.9, 1), ("Rocks", 4.6, 7)])
#Se utiliza esta funcion para transformar un arreglo estructurado a un arreglo de records
B = np.core.records.fromarrays(A.T, names='col1, col2, col3', formats = 'S8, f8, i8')
#Un arreglo de records se diferencia en que se puede acceder a sus valores de forma individual o segun grupos de nombres
#Tambien se puede acceder segun tipos de datos, pero en este ejemplo estos no estan definidos
print(B[0])
print(B.col1)
print(B.col2[0])
print(B.col3[1])

In [ ]:
#83
#Se crea un arreglo de 1 millon de elementos aleatorios
A = np.random.rand(1000000)
#Se usa %timeit para medir cuanto tarda cada operacion
#Potencia utilizando la funcion power
print("tiempo con power()")
%timeit np.power(A, 3)
#Potencia utilizando multiplicacion simple
print("tiempo multiplicando")
%timeit A*A*A
#Potencia multiplicando con einsum
print("tiempo multiplicando con einsum")
%timeit np.einsum('i,i,i->i',A,A,A)

In [ ]:
#85
#Creando un arreglo aleatorio de 10x3
A = np.random.randint(0,5,(10,3))
#Identificando las filas con elementos iguales
B = np.logical_and.reduce(A[:,1:] == A[:,:-1], axis=1)
#Imprimiendo el arreglo menos las filas iguales
C = A[~B]
print("Arreglo original:")
print(A)
print("\nArreglo omitiendo filas con elementos iguales:")
print(C)

In [24]:
lista=[25,12,15,66,12.5] 
vector=np.array(lista) 
print(vector)

[25.  12.  15.  66.  12.5]


In [25]:
print(vector[:4])

[25. 12. 15. 66.]
